import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Sidebar from '../components/sidebar';
import Header from '../components/header';
import Styles from "../styles/Home.module.scss"
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Omra Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container-fluid'>
  
        <div className="row">
          <div className="col-2">
          <Sidebar/>
          </div>
          <div className="col-10 header">
          <Header/>
        {/* pages goes code here start */}


          <div className="container" style={{marginTop:"60px"}}>
            <div className="row">
              <div className="col-4">
                <div className={Styles.boxone}>
<Link href="#">BANKING</Link>
                </div>
              </div>
              <div className="col-4">
              <div className={Styles.boxtwo}>
              <Link href="#">JD</Link>
                </div>
              </div>
              <div className="col-4">
              <div className={Styles.boxthree}>
              <Link href="#">BPO</Link>
                </div>
              </div>
            </div>
<section className={Styles.sectiontwo}>
            <h2>Instrucation To Go With Flow</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
            <Image src="/image/ss.jpg" width={1300} height={400} priority />
            </section>
          </div>

        {/* pages goes code here end */}
          </div>
        </div>
        
      </div>
      
    </div>
  )
}
